-- The ToME factions

factions.new("UNDEAD", "undeads")
factions.new("ANIMAL", "animals")
factions.new("SAURON", "sauron")
factions.new("ISENGARD", "isengard")
factions.new("ROHAN", "rohan")
factions.new("GONDOR", "gondor")
factions.new("ELF", "elf")
factions.new("DWARF", "dwarf")
factions.new("ENT", "ent")

factions.set_friendliness(FACTION_ANIMAL, FACTION_DUNGEON, -50)
factions.set_friendliness(FACTION_ANIMAL, FACTION_UNDEAD, -75)
factions.set_friendliness(FACTION_ANIMAL, FACTION_SAURON, -50)
factions.set_friendliness(FACTION_ANIMAL, FACTION_ISENGARD, -50)
factions.set_friendliness(FACTION_ANIMAL, FACTION_PLAYER, -10)
factions.set_friendliness(FACTION_ANIMAL, FACTION_UNDEAD, -75)
factions.set_friendliness(FACTION_ANIMAL, FACTION_SAURON, -50)
factions.set_friendliness(FACTION_ANIMAL, FACTION_ISENGARD, -50)
factions.set_friendliness(FACTION_ANIMAL, FACTION_ENT, 20)

factions.set_friendliness(FACTION_SAURON, FACTION_DUNGEON, 50)
factions.set_friendliness(FACTION_SAURON, FACTION_UNDEAD, 25)
factions.set_friendliness(FACTION_SAURON, FACTION_ISENGARD, 25)
factions.set_friendliness(FACTION_SAURON, FACTION_ISENGARD, -10)
factions.set_friendliness(FACTION_SAURON, FACTION_ANIMAL, -75)
factions.set_friendliness(FACTION_SAURON, FACTION_ROHAN, -100)
factions.set_friendliness(FACTION_SAURON, FACTION_GONDOR, -100)
factions.set_friendliness(FACTION_SAURON, FACTION_ELF, -100)
factions.set_friendliness(FACTION_SAURON, FACTION_DWARF, -100)
factions.set_friendliness(FACTION_SAURON, FACTION_PLAYER, -100)
factions.set_friendliness(FACTION_SAURON, FACTION_ENT, -100)

factions.set_friendliness(FACTION_ISENGARD, FACTION_DUNGEON, 50)
factions.set_friendliness(FACTION_ISENGARD, FACTION_UNDEAD, 15)
factions.set_friendliness(FACTION_ISENGARD, FACTION_SAURON, -10)
factions.set_friendliness(FACTION_ISENGARD, FACTION_ANIMAL, -75)
factions.set_friendliness(FACTION_ISENGARD, FACTION_GONDOR, -100)
factions.set_friendliness(FACTION_ISENGARD, FACTION_ROHAN, -100)
factions.set_friendliness(FACTION_ISENGARD, FACTION_ELF, -100)
factions.set_friendliness(FACTION_ISENGARD, FACTION_DWARF, -100)
factions.set_friendliness(FACTION_ISENGARD, FACTION_PLAYER, -100)
factions.set_friendliness(FACTION_ISENGARD, FACTION_ENT, -100)

factions.set_friendliness(FACTION_ROHAN, FACTION_DUNGEON, -50)
factions.set_friendliness(FACTION_ROHAN, FACTION_UNDEAD, -100)
factions.set_friendliness(FACTION_ROHAN, FACTION_ISENGARD, -100)
factions.set_friendliness(FACTION_ROHAN, FACTION_SAURON, -100)
factions.set_friendliness(FACTION_ROHAN, FACTION_PLAYER, 25)
factions.set_friendliness(FACTION_ROHAN, FACTION_GONDOR, 25)
factions.set_friendliness(FACTION_ROHAN, FACTION_DWARF, 25)
factions.set_friendliness(FACTION_ROHAN, FACTION_ELF, 25)
factions.set_friendliness(FACTION_ROHAN, FACTION_ENT, 1)

factions.set_friendliness(FACTION_GONDOR, FACTION_DUNGEON, -50)
factions.set_friendliness(FACTION_GONDOR, FACTION_UNDEAD, -100)
factions.set_friendliness(FACTION_GONDOR, FACTION_ISENGARD, -90)
factions.set_friendliness(FACTION_GONDOR, FACTION_SAURON, -90)
factions.set_friendliness(FACTION_GONDOR, FACTION_ROHAN, 20)
factions.set_friendliness(FACTION_GONDOR, FACTION_PLAYER, 20)
factions.set_friendliness(FACTION_GONDOR, FACTION_DWARF, 20)
factions.set_friendliness(FACTION_GONDOR, FACTION_ELF, 20)
factions.set_friendliness(FACTION_GONDOR, FACTION_ENT, 1)

factions.set_friendliness(FACTION_ELF, FACTION_DUNGEON, -50)
factions.set_friendliness(FACTION_ELF, FACTION_UNDEAD, -100)
factions.set_friendliness(FACTION_ELF, FACTION_ISENGARD, -100)
factions.set_friendliness(FACTION_ELF, FACTION_SAURON, -100)
factions.set_friendliness(FACTION_ELF, FACTION_ROHAN, 15)
factions.set_friendliness(FACTION_ELF, FACTION_PLAYER, 50)
factions.set_friendliness(FACTION_ELF, FACTION_DWARF, 10)
factions.set_friendliness(FACTION_ELF, FACTION_GONDOR, 20)
factions.set_friendliness(FACTION_ELF, FACTION_ANIMAL, 80)
factions.set_friendliness(FACTION_ELF, FACTION_ENT, 20)

factions.set_friendliness(FACTION_DWARF, FACTION_DUNGEON, -50)
factions.set_friendliness(FACTION_DWARF, FACTION_UNDEAD, -100)
factions.set_friendliness(FACTION_DWARF, FACTION_ISENGARD, -100)
factions.set_friendliness(FACTION_DWARF, FACTION_ISENGARD, -100)
factions.set_friendliness(FACTION_DWARF, FACTION_ROHAN, 15)
factions.set_friendliness(FACTION_DWARF, FACTION_PLAYER, 15)
factions.set_friendliness(FACTION_DWARF, FACTION_ELF, 10)
factions.set_friendliness(FACTION_DWARF, FACTION_ENT, -5)

factions.set_friendliness(FACTION_UNDEAD, FACTION_DUNGEON, 50)
factions.set_friendliness(FACTION_UNDEAD, FACTION_SAURON, 15)
factions.set_friendliness(FACTION_UNDEAD, FACTION_ISENGARD, 25)
factions.set_friendliness(FACTION_UNDEAD, FACTION_ANIMAL, -75)
factions.set_friendliness(FACTION_UNDEAD, FACTION_ROHAN, -100)
factions.set_friendliness(FACTION_UNDEAD, FACTION_GONDOR, -100)
factions.set_friendliness(FACTION_UNDEAD, FACTION_ELF, -100)
factions.set_friendliness(FACTION_UNDEAD, FACTION_DWARF, -100)
factions.set_friendliness(FACTION_UNDEAD, FACTION_PLAYER, -100)
factions.set_friendliness(FACTION_UNDEAD, FACTION_ENT, -100)

factions.set_friendliness(FACTION_ENT, FACTION_DUNGEON, -50)
factions.set_friendliness(FACTION_ENT, FACTION_ANIMAL, 20)
factions.set_friendliness(FACTION_ENT, FACTION_SAURON, -100)
factions.set_friendliness(FACTION_ENT, FACTION_ISENGARD, -100)
factions.set_friendliness(FACTION_ENT, FACTION_ROHAN, 1)
factions.set_friendliness(FACTION_ENT, FACTION_GONDOR, 1)
factions.set_friendliness(FACTION_ENT, FACTION_ELF, 20)
factions.set_friendliness(FACTION_ENT, FACTION_DWARF, -5)
factions.set_friendliness(FACTION_ENT, FACTION_UNDEAD, -100)
factions.set_friendliness(FACTION_ENT, FACTION_PLAYER, 0)

factions.set_friendliness(FACTION_PLAYER, FACTION_DUNGEON, -100)
factions.set_friendliness(FACTION_PLAYER, FACTION_ANIMAL, -10)
factions.set_friendliness(FACTION_PLAYER, FACTION_SAURON, -100)
factions.set_friendliness(FACTION_PLAYER, FACTION_ISENGARD, -100)
factions.set_friendliness(FACTION_PLAYER, FACTION_ROHAN, 25)
factions.set_friendliness(FACTION_PLAYER, FACTION_GONDOR, 20)
factions.set_friendliness(FACTION_PLAYER, FACTION_ELF, 50)
factions.set_friendliness(FACTION_PLAYER, FACTION_DWARF, 15)
factions.set_friendliness(FACTION_PLAYER, FACTION_UNDEAD, -100)
factions.set_friendliness(FACTION_PLAYER, FACTION_ENT, 0)
