init_skill(SKILL_AIR, 		"Air")
init_skill(SKILL_ALCHEMY, 	"Alchemy")
init_skill(SKILL_ANTIMAGIC, 	"Antimagic")
init_skill(SKILL_ARCHERY, 	"Archery")
init_skill(SKILL_BEAR, 		"BEAR")
init_skill(SKILL_BOULDER, 	"Boulder-throwing")
init_skill(SKILL_COMBAT, 	"Combat")
init_skill(SKILL_CONVEYANCE, 	"Conveyance")
init_skill(SKILL_DAEMON, 	"Demonology")
init_skill(SKILL_DEVICE, 	"Magic-device")
init_skill(SKILL_DISARMING, 	"Disarming")
init_skill(SKILL_DODGE, 	"Dodging")
init_skill(SKILL_EARTH, 	"Earth")
init_skill(SKILL_FIRE, 		"Fire")
init_skill(SKILL_HAND, 		"Barehand-combat")
init_skill(SKILL_LORE, 		"Monster-lore")
init_skill(SKILL_MAGIC, 	"Magic")
init_skill(SKILL_MANA, 		"Mana")
init_skill(SKILL_MASTERY, 	"Weaponmastery")
init_skill(SKILL_MIMICRY, 	"Mimicry")
init_skill(SKILL_MINDCRAFT, 	"Mindcraft")
init_skill(SKILL_NECROMANCY, 	"Necromancy")
init_skill(SKILL_POSSESSION, 	"Possession")
init_skill(SKILL_PRESERVATION, 	"Corpse-preservation")
init_skill(SKILL_SNEAK, 	"Sneakiness")
init_skill(SKILL_SORCERY, 	"Sorcery")
init_skill(SKILL_SPIRITUALITY, 	"Spirituality")
init_skill(SKILL_STEALING, 	"Stealing")
init_skill(SKILL_STEALTH, 	"Stealth")
init_skill(SKILL_SUMMON, 	"Summoning")
init_skill(SKILL_SYMBIOTIC, 	"Symbiosis")
init_skill(SKILL_THAUMATURGY, 	"Thaumaturgy")
init_skill(SKILL_UDUN, 		"Udun")
init_skill(SKILL_WATER, 	"Water")

init_ability(AB_TREE_WALK,	"Tree walking")
init_ability(AB_PERFECT_CASTING,"Perfect casting")
init_ability(AB_UNDEAD_FORM,	"Undead Form")
init_ability(AB_TRAPPING,	"Trapping")
init_ability(AB_MAX_BLOW1,	"Extra Max Blow(1)")
init_ability(AB_MAX_BLOW2,	"Extra Max Blow(2)")
